usr/include/node
# keep old paths for smooth transition
deps/openssl/openssl/apps/openssl.cnf usr/include/nodejs
src/*.h usr/include/nodejs/src
deps/v8/include/cppgc/*.h usr/include/nodejs/deps/v8/include/cppgc
deps/v8/include/cppgc/internal/*.h usr/include/nodejs/deps/v8/include/cppgc/internal
deps/v8/include/*.h usr/include/nodejs/deps/v8/include
deps/v8/include/libplatform/*.h usr/include/nodejs/deps/v8/include/libplatform
common.gypi usr/include/nodejs
